//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderPart
    {
        public PurchaseOrderPart()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int PurchaseOrderPartId { get; set; }
        public int PurchaseOrderId { get; set; }
        public int PartId { get; set; }
        public int Quantity { get; set; }
        public decimal Cost { get; set; }
        public decimal ExtendedCost { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
