//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ReceiptId { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public int PurchaseOrderPartId { get; set; }
        public int Quantity { get; set; }
        public decimal TotalCost { get; set; }
        public decimal ShippingAndHandling { get; set; }
    
        public virtual PurchaseOrderPart PurchaseOrderPart { get; set; }
    }
}
