//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReturn
    {
        public int SalesReturnId { get; set; }
        public int ShipmentPartId { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual ShipmentPart ShipmentPart { get; set; }
    }
}
