//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public SalesOrder()
        {
            this.SalesOrderParts = new HashSet<SalesOrderPart>();
            this.Shipments = new HashSet<Shipment>();
        }
    
        public int SalesOrderNumber { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<decimal> OrderCost { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<SalesOrderPart> SalesOrderParts { get; set; }
        public virtual ICollection<Shipment> Shipments { get; set; }
    }
}
