//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderPart
    {
        public int SalesOrderPartId { get; set; }
        public int SalesOrderNumber { get; set; }
        public int PartID { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal ExtendedPrice { get; set; }
        public decimal UnitCost { get; set; }
        public decimal ExtendedCost { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
