//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public Shipment()
        {
            this.ShipmentParts = new HashSet<ShipmentPart>();
        }
    
        public int ShipmentId { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public int OrderNumber { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual ICollection<ShipmentPart> ShipmentParts { get; set; }
    }
}
