//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentPart
    {
        public ShipmentPart()
        {
            this.SalesReturns = new HashSet<SalesReturn>();
        }
    
        public int ShipmentPartId { get; set; }
        public int ShipmentId { get; set; }
        public int SalesOrderPartId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitCost { get; set; }
        public decimal ExtendedCost { get; set; }
    
        public virtual ICollection<SalesReturn> SalesReturns { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
