//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public int VendorId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}
